services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  hono:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: ["node", "/app/dist/index.js"]
    labels:
      - "traefik.http.routers.hono.rule=Host(`shop-api.prpbooks.com`)"
      - "traefik.http.services.hono.loadbalancer.server.port=3000"
